version: "3"
services:
  script-python:
    build: .
    links:
     - pg-container
    restart: on-failure
  pg-container:
    build:
      context: .
      dockerfile: Dockerfile-db
    environment: 
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test_db
    volumes: 
      - pg-data:/var/lib/postgresql/data
volumes: 
  pg-data: {}
